---
- name: Deploy Vikunja with podman compose on Rocky Linux 9
  hosts: localhost
  connection: local
  become: true
  become_user: root

- import_playbook: ./ansiblePlaybooks/initialize-host.yml
- import_playbook: ./ansiblePlaybooks/update-packages.yml
- import_playbook: ./ansiblePlaybooks/install-podman.yml
- import_playbook: ./ansiblePlaybooks/install-cockpit.yml
- import_playbook: ./ansiblePlaybooks/configure-vikunja.yml
- import_playbook: ./ansiblePlaybooks/create-user.yml

    