version: '3'

services:
  api:
    image: docker.io/vikunja/api
    environment:
      VIKUNJA_DATABASE_TYPE: sqlite
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
      VIKUNJA_SERVICE_FRONTENDURL: ${DOMAIN}
      VIKUNJA_SERVICE_ENABLEREGISTRATION:  ${ENABLEREGISTRATION}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ./files:/app/vikunja/files
      - ./db:/db
    restart: unless-stopped
  frontend:
    image: docker.io/vikunja/frontend
    restart: unless-stopped
  caddy:
    image: docker.io/caddy
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - api
      - frontend
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro