---
- name: Create non root admin user
  hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
    - name: Create non root admin user and grant permissions to vikunja folder
      ansible.builtin.user:
        name: micah
        shell: /bin/bash
        groups: wheel, vikunjaAdmins
        append: yes
    
    - name: Create non root vikunja user and grant permissions to vikunja folder
      ansible.builtin.user:
        name: vikunja
        shell: /bin/bash
        uid: 1005
        groups: vikunjaAdmins
        append: yes