- name: Ensure system is initialized
  hosts: localhost
  connection: local
  become: true
  become_user: root
  gather_facts: no # is necessary because setup.py depends on Python too

  pre_tasks:
  - name: "Make sure remote system is initialized correctly"
    raw: 'ln -s /usr/bin/python3 /usr/bin/python'
    register: set_symlink
    failed_when: set_symlink.rc != 0 and set_symlink.rc != 1 